name: py36
channels:
- menpo
- defaults
dependencies:
- python=3.6
- dlib
- pip
- pip:
  - matplotlib
  - scikit-image
  - torch
  - opencv-python
  - colormap
  - easydev
  - k3d==2.7.4
  - tqdm
  - six
  - requests